const state={balance:245800,hidden:false,transactions:[{title:'Salary credit',sub:'Today • 09:20',amount:180000,type:'in'},{title:'Transfer to UBA',sub:'Yesterday • 16:42',amount:-25000,type:'out'},{title:'MTN Airtime',sub:'Aug 24 • 12:11',amount:-2000,type:'out'},{title:'Money received',sub:'Aug 23 • 18:04',amount:15000,type:'in'}]};
const money=n=>new Intl.NumberFormat('en-NG',{style:'currency',currency:'NGN'}).format(n);
function renderTransactions(){const html=state.transactions.map(t=>`<div class="transaction"><div class="tx-icon">${t.type==='in'?'↓':'↑'}</div><div class="tx-main"><div class="tx-title">${t.title}</div><div class="tx-sub">${t.sub}</div></div><div class="tx-amount ${t.type==='in'?'positive':'negative'}">${t.type==='in'?'+':''}${money(t.amount)}</div></div>`).join('');document.querySelector('#recentTransactions').innerHTML=html;document.querySelector('#allTransactions').innerHTML=html}
function showPage(page){document.querySelectorAll('.page').forEach(x=>x.classList.remove('active-page'));document.getElementById(page)?.classList.add('active-page');document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.page===page));const titles={home:'Good afternoon, Chukwudi',transfer:'Send money',airtime:'Airtime & Data',bills:'Pay bills',history:'Transaction history'};document.getElementById('pageTitle').textContent=titles[page]||'NaijaPay'}
function toast(msg){const t=document.getElementById('toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2500)}
function updateBalance(){document.getElementById('balance').textContent=state.hidden?'••••••••':money(state.balance)}
document.addEventListener('click',e=>{const target=e.target.closest('[data-page]');if(target){e.preventDefault();showPage(target.dataset.page)}});
document.getElementById('toggleBalance').onclick=()=>{state.hidden=!state.hidden;document.getElementById('toggleBalance').textContent=state.hidden?'Show':'Hide';updateBalance()};
document.getElementById('addMoney').onclick=()=>toast('Demo only: connect a payment provider to fund wallets.');
document.getElementById('transferForm').onsubmit=e=>{e.preventDefault();const amount=Number(document.getElementById('amount').value);if(amount>state.balance)return toast('Insufficient demo balance.');state.balance-=amount;state.transactions.unshift({title:`Transfer to ${document.getElementById('bank').value}`,sub:'Just now • Demo transaction',amount:-amount,type:'out'});renderTransactions();updateBalance();e.target.reset();toast('Transfer created in demo mode. No money was moved.')};
document.getElementById('airtimeForm').onsubmit=e=>{e.preventDefault();const amount=Number(document.getElementById('topupAmount').value);if(amount>state.balance)return toast('Insufficient demo balance.');state.balance-=amount;state.transactions.unshift({title:`${document.getElementById('network').value} ${document.getElementById('topupType').value}`,sub:'Just now • Demo transaction',amount:-amount,type:'out'});renderTransactions();updateBalance();e.target.reset();toast('Top-up simulated successfully.')};
document.getElementById('billForm').onsubmit=e=>{e.preventDefault();const amount=Number(document.getElementById('billAmount').value);if(amount>state.balance)return toast('Insufficient demo balance.');state.balance-=amount;state.transactions.unshift({title:document.getElementById('billType').value,sub:'Just now • Demo transaction',amount:-amount,type:'out'});renderTransactions();updateBalance();e.target.reset();toast('Bill payment simulated successfully.')};
renderTransactions();updateBalance();
